In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("datasets/covid_global.csv")

In [13]:
df.head()

,iso_code,location,date,new_cases,aged_65_older,hosp_patients,icu_patients,people_vaccinated,population,days,percentage_population,weeks
0,BEL,Belgium,2021-08-09,4653.0,18.571,462.0,120.0,8251843.0,11632334.0,0,0.709388,0
1,BEL,Belgium,2021-08-10,1748.0,18.571,465.0,120.0,8267925.0,11632334.0,1,0.710771,0
2,BEL,Belgium,2021-08-11,2609.0,18.571,454.0,124.0,8284331.0,11632334.0,2,0.712181,0
3,BEL,Belgium,2021-08-12,2119.0,18.571,475.0,132.0,8301389.0,11632334.0,3,0.713648,0
4,BEL,Belgium,2021-08-13,2014.0,18.571,496.0,136.0,8315496.0,11632334.0,4,0.714860,0

In [14]:
df_country = df[df.iso_code == "BEL"]

In [15]:
df_country

,iso_code,location,date,new_cases,aged_65_older,hosp_patients,icu_patients,people_vaccinated,population,days,percentage_population,weeks
0,BEL,Belgium,2021-08-09,4653.0,18.571,462.0,120.0,8251843.0,11632334.0,0,0.709388,0
1,BEL,Belgium,2021-08-10,1748.0,18.571,465.0,120.0,8267925.0,11632334.0,1,0.710771,0
2,BEL,Belgium,2021-08-11,2609.0,18.571,454.0,124.0,8284331.0,11632334.0,2,0.712181,0
3,BEL,Belgium,2021-08-12,2119.0,18.571,475.0,132.0,8301389.0,11632334.0,3,0.713648,0
4,BEL,Belgium,2021-08-13,2014.0,18.571,496.0,136.0,8315496.0,11632334.0,4,0.714860,0
...,...,...,...,...,...,...,...,...,...,...,...,...
96,BEL,Belgium,2021-11-13,0.0,18.571,1948.0,391.0,8772384.0,11632334.0,96,0.754138,13
97,BEL,Belgium,2021-11-14,0.0,18.571,1948.0,391.0,8772471.0,11632334.0,97,0.754145,13
98,BEL,Belgium,2021-11-15,27762.0,18.571,1948.0,391.0,8774700.0,11632334.0,98,0.754337,14
99,BEL,Belgium,2021-11-16,12388.0,18.571,1948.0,391.0,8777117.0,11632334.0,99,0.754545,14
100,BEL,Belgium,2021-11-17,18437.0,18.571,1948.0,391.0,8777117.0,11632334.0,100,0.754545,14